version: '3.8'

services:
  # MongoDB Service
  db:
    image: mongo:latest
    container_name: student-finder-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  # Backend Service
  backend:
    build: ./backend
    container_name: student-finder-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/student_finder_db
    depends_on:
      - db

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: student-finder-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
